### ISSUE TITLE
"Error: initialization failed!"

### ISSUE THREAD

**Issue by vigi86** [open-keychain/open-keychain#2905]
## Expected Behavior
Well, not getting this footer message.

## Current Behavior
As soon as I open the App, a footer appears "Error: initialization failed!"
If I go to Settings, no matter where I was before (Keys, Encrypt/Decrypt, Apps, Backup), when I return from Settings, the footer appears.
If I toggle Apps and return to OKC, the footer appears (except when in settings).

I tried deleting the cache, and also reinstalled the app.

## Steps to Reproduce (for bugs)
1. open app is enough (or as described above)

## Your Environment

* Android Version: 13
* Device Model: Samsung Galaxy S20 Ultra 5G
* OpenKeychain Version: 6.0.4
* From Google Play or F-Droid?: Google Play & F-Droid has same behaviour.

**Comment by rafaelazvdo** [comment]
Try decrypting the key with Kleopatra on Linux or Gpg4Win on Windows and then try importing the .asc file into OPK.

**Comment by vigi86** [comment]
> Try decrypting the key with Kleopatra on Linux or Gpg4Win on Windows and then try importing the .asc file into OPK.

This issue is without any keys imported. It's on a fresh install.

**Comment by krakeVizva** [comment]
Marcel Bokhorst answered me for a similiar Problem with "fairemail":In fairemail--->""""Please go to the settings via the navigation menu (left side menu), tap on "Manual setup and account options", tap on "Identities", long press on the used identity and select to reset the keys.

Bitte gehen Sie über das Navigationsmenü (linkes Menü) zu den Einstellungen, tippen Sie auf "Manuelle Einrichtung und Kontooptionen", tippen Sie auf "Identitäten", drücken Sie lange auf die verwendete Identität und wählen Sie, um die Tasten zurückzusetzen.

This should solve the problem, correct?
Damit sollte das Problem gelöst sein, richtig?"""

Maybe you use fairemail and you could solve your problem

**Comment by MykelSIlver** [comment]
> Marcel Bokhorst answered me for a similiar Problem with "fairemail":In fairemail--->""""Please go to the settings via the navigation menu (left side menu), tap on "Manual setup and account options", tap on "Identities", long press on the used identity and select to reset the keys.
> 
> Bitte gehen Sie über das Navigationsmenü (linkes Menü) zu den Einstellungen, tippen Sie auf "Manuelle Einrichtung und Kontooptionen", tippen Sie auf "Identitäten", drücken Sie lange auf die verwendete Identität und wählen Sie, um die Tasten zurückzusetzen.
> 
> This should solve the problem, correct? Damit sollte das Problem gelöst sein, richtig?"""
> 
> Maybe you use fairemail and you could solve your problem

There is no Account Options. There is also no Manual setup in Openkeychain. This is a pure related  to Openkeychain.

**Comment by galets** [comment]
I am experiencing the same exact issue. I completely reset the app (clear stotage), and yet I am still getting "Error initialization failed". This is how it looks:

![image](https://github.com/user-attachments/assets/9b81b966-c24c-4735-96d6-f988e424d29a)

Also I am noticing that an app does not lock anymore. Once keychain is unlocked, it stays unlocked forever. Expected behavior is that on screensaver it must force you to re-enter unlock password

**Comment by vigi86** [comment]
Update: the problem suddenly disappeared magically.

> Marcel Bokhorst answered me for a similiar Problem with "fairemail":In fairemail--->""""Please go to the settings via the navigation menu (left side menu), tap on "Manual setup and account options", tap on "Identities", long press on the used identity and select to reset the keys.
> 
> Bitte gehen Sie über das Navigationsmenü (linkes Menü) zu den Einstellungen, tippen Sie auf "Manuelle Einrichtung und Kontooptionen", tippen Sie auf "Identitäten", drücken Sie lange auf die verwendete Identität und wählen Sie, um die Tasten zurückzusetzen.
> 
> This should solve the problem, correct? Damit sollte das Problem gelöst sein, richtig?"""
> 
> Maybe you use fairemail and you could solve your problem

Yes, I use FairEmail Free Version. There is no "Schlüssel zurücksetzen / reset keys", however.
But yeah, as mentioned, the problem is solved for me. 
I leave the issue open for @galets

**Comment by galets** [comment]
As far as I'm concerned, I am no longer affected by a problem, but that's because I switched back to my old phone (samsung s22+ from pixel9).

I still have the pixel9 in my possession, and I can debug the issue further, except I cannot build the thing. There is a bunch of dependent packages which I no longer can locate anywhere. If one of the devs can help me build the source, I could help work on this. I'm pretty sure it affects more than two people. Otherwise, I guess this can be closed

**Comment by MykelSIlver** [comment]
Still exists on Pixel 8 pro.

As far as I see the issue is still there.

**Comment by galets** [comment]
My offer to debug this still stands

**Comment by johandroid** [comment]
I have this issue in Pixel 9 Pro with GrapheneOS

**Comment by shaohme** [comment]
I have the same problem on Pixel 7 with GrapheneOS 😦

**Comment by shaohme** [comment]
For some reason it disappeared after clearing OpenKeychain storage+cache and update to GrapheneOS 2024092900. Don't know if any of this has an effect or in which order ...

**Comment by OverlordAdmin** [comment]
I kept getting the same error. It was popping up continuously when opening the app! Annoying to say the least.

Resolved it easily though...

Removed my visa card with NFC from my phone cover. Haven't had the issue since. Adding the card to the cover restores the issue. 😀

**Comment by vigi86** [comment]
> I kept getting the same error. It was popping up continuously when opening the app! Annoying to say the least.
> 
> Resolved it easily though...
> 
> Removed my visa card with NFC from my phone cover. Haven't had the issue since. Adding the card to the cover restores the issue. 😀

OH MY GOD! That's it!!! Hahaha
I just tried it. I had my building access badge in my phone cover before, when having this issue. I never thought it would be NFC that was causing the issue. 😂

### Reproduce

1. Enable NFC
2. hold a card that supports NFC to the phone
3. footer with error message appears

### Solution

Remove NFC card from phone cover or disable NFC on phone.

OK, now we found out what causes the footer. 
Question is: why does it appear?? Why does Open Keychain interact with NFC?

**Comment by rcorre** [comment]
Yup, I can repro this on pixel8. I have a phone case with a card compartment, and I get "initialization failed" (and a haptic buzz) every time I open the app. I removed the card, and the issue went away.

**Comment by rcorre** [comment]
I'm able to stop the issue by disabling NFC globally, but it doesn't look like you can disable NFC per-app: https://android.stackexchange.com/questions/258261/turn-off-nfc-permission-for-specific-app
